---
driver:
  name: vagrant

provisioner:
  name: chef_zero

  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: rhel-7.3

suites:
  - name: default
    run_list:
      - recipe[aws::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
